"""
Disposition payload templates — ported verbatim from
emily-ai-be/disposition_templates.py.
"""

BASE_DISPOSITION_PAYLOAD = {
    "deRowid": None,  # Set dynamically from GetDebtor API
    "opId": "EAI",
    "coRowid": None,
    "cosRowid": None,
    "phRowid": None,
    "note": None,
    "pinNote": False,
    "action": None,  # Set by disposition config
    "language": None,
    "status": None,
    "concentType": None,
    "callType": "Incoming",
    "runplane": None,
    "dueDate": None,
    "dueDate1": None,
    "remindertime": None,
    "remindertime1": None,
    "noRPC": None,
    "time": None,
    "contactChanel": "CALL",
    "chanelNumber": None,
    "repeatperiod": None,
    "repeatfrequency": None,
    "rpcFlag": None,
    "coType": None,
    "coclass": None,
    "priority": None,
    "amount": None,
    "coWho": None,
    "paymethod": None,
    "attchment": None,
    "description": None,
    "contactName": None,
    "createForGroupFiles": False,
    "createForCcprReport": False,
    "assignToOpId": None,
    "departmentTL": None,
    "cDate": None,
    "ctime": None,
    "unspecifiedAmount": None,
    "cosignerName": None,
    "inconvenienceDetail": {
        "createForGroupFiles": False,
        "deRowid": None,
        "at_row_Id": None,
        "deCosRowid": None,
        "day": None,
        "dncAtNight": None,
        "dncInWorkingHours": None,
        "dncAtWeekend": None,
        "cDate": None,
        "mDate": None,
        "opId": None,
        "method": None,
        "inConvenienceTimeList": None,
    },
    "convenienceDetail": {},
    "disputeReson": {
        "requestValidationDocumentFlag": False,
        "type": None,
        "note": None,
        "reason": None,
        "amount": None,
        "amountType": None,
        "attorneyName": None,
        "attorneyPhone": None,
        "attorneyEmail": None,
        "attorneyAddress": None,
        "caseNumber": None,
        "courtName": None,
        "caseType": None,
        "districtBankruptcy": None,
        "contactAttemptNote": None,
        "chapterFiled": None,
        "dateFiled": None,
        "contactCreditor": None,
        "files": [None],
    },
    "legalRequest": None,
    "dispositionDetail": {
        "dispositionId": None,
        "dispositionName": None,
        "categoryId": None,
        "categoryName": None,
        "collectcoDesposition": None,
        "categoryType": None,
        "description": None,
        "forDepartment": None,
        "isActiveForRunplan": None,
        "name": None,  # Extra field not in schema but accepted by API
    },
    "settlementOfferDetails": {
        "offeredAmount": None,
        "offeredInstallment": None,
        "offeredInstallmentAmount": None,
        "offeredFrequency": None,
        "offeredStartDate": None,
        "offeredEndDate": None,
    },
    "followUpEmail": {
        "promise": {"amount": None, "method": None},
        "followUpDate": None,
        "followUpTime": None,
        "priority": None,
        "contactChanel": None,
        "chanelNumber": None,
    },
    "followUpSMS": {
        "promise": {"amount": None, "method": None},
        "followUpDate": None,
        "followUpTime": None,
        "priority": None,
        "contactChanel": None,
        "chanelNumber": None,
    },
    "followUpCall": {
        "promise": {"amount": None, "method": None},
        "followUpDate": None,
        "followUpTime": None,
        "priority": None,
        "contactChanel": None,
        "chanelNumber": None,
    },
    "fileTransfer": None,
    "insuranceEmails": [],
}
